name = "ClimaCartesianIndices"
uuid = "afc79dc6-9922-4b50-ae92-da7b5116c2c8"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[compat]
Aqua = "0.8"
Test = "1"
julia = "1.10"

[targets]
test = ["Test", "Aqua"]
